/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package localinventorymanager.Classes;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.*;
/**
 *
 * @author XD
 */
public class App extends javax.swing.JFrame {
    final Color WHITE=new Color(255,255,255);
    final Color RED=new Color(255,0,0);
    final Color HOVERCOLOR=new Color(99, 190, 255);
    final Color ORIGINALTEXTCOLOR=new Color(0,102,204);
    final Cursor HAND=new Cursor(Cursor.HAND_CURSOR);
    final Cursor NORMAL=new Cursor(Cursor.DEFAULT_CURSOR);
    /**
     * Creates new form App
     */
    public App() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        root = new javax.swing.JPanel();
        mainContent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        products = new javax.swing.JList<>();
        imagePane = new javax.swing.JPanel();
        productImage = new javax.swing.JLabel();
        searchBar = new javax.swing.JTextField();
        searchButton = new javax.swing.JPanel();
        searchButtonTxt = new javax.swing.JLabel();
        employeeInfo = new javax.swing.JLabel();
        employeePicPane = new javax.swing.JPanel();
        employeeImage = new javax.swing.JLabel();
        buttonsPane = new javax.swing.JPanel();
        quickStock = new javax.swing.JPanel();
        quickStockTxt = new javax.swing.JLabel();
        quickSell = new javax.swing.JPanel();
        quickSellTxt = new javax.swing.JLabel();
        manage = new javax.swing.JPanel();
        manageTxt = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        logoutTxt = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout());

        root.setBackground(new java.awt.Color(51, 0, 51));
        root.setLayout(new java.awt.BorderLayout());

        mainContent.setBackground(new java.awt.Color(0, 102, 153));
        mainContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        products.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item2", "Item3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        products.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        products.setToolTipText("");
        products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(products);

        mainContent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 124, 498, 209));

        imagePane.setBackground(new java.awt.Color(255, 255, 255));
        imagePane.setLayout(new java.awt.GridLayout());

        productImage.setText("Product");
        imagePane.add(productImage);

        mainContent.add(imagePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 140, 130));

        searchBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchBarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchBarMouseExited(evt);
            }
        });
        mainContent.add(searchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 351, 353, 20));

        searchButton.setBackground(new java.awt.Color(255, 255, 255));
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchButtonMouseExited(evt);
            }
        });
        searchButton.setLayout(new java.awt.GridLayout());

        searchButtonTxt.setForeground(new java.awt.Color(0, 102, 204));
        searchButtonTxt.setText("Search product");
        searchButton.add(searchButtonTxt);

        mainContent.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 351, 133, 22));

        employeeInfo.setText("Bienvenido usuario");
        mainContent.add(employeeInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 20, -1, -1));

        employeePicPane.setBackground(new java.awt.Color(255, 255, 255));

        employeeImage.setBackground(new java.awt.Color(255, 255, 255));
        employeeImage.setText("Employee pic");

        javax.swing.GroupLayout employeePicPaneLayout = new javax.swing.GroupLayout(employeePicPane);
        employeePicPane.setLayout(employeePicPaneLayout);
        employeePicPaneLayout.setHorizontalGroup(
            employeePicPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePicPaneLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(employeeImage)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        employeePicPaneLayout.setVerticalGroup(
            employeePicPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeePicPaneLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(employeeImage)
                .addGap(39, 39, 39))
        );

        mainContent.add(employeePicPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 6, -1, -1));

        buttonsPane.setBackground(new java.awt.Color(0, 102, 153));
        buttonsPane.setForeground(new java.awt.Color(102, 255, 102));

        quickStock.setBackground(new java.awt.Color(255, 255, 255));
        quickStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quickStockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                quickStockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                quickStockMouseExited(evt);
            }
        });
        quickStock.setLayout(new java.awt.GridLayout());

        quickStockTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        quickStockTxt.setForeground(new java.awt.Color(0, 102, 204));
        quickStockTxt.setText("Quick stock");
        quickStock.add(quickStockTxt);

        quickSell.setBackground(new java.awt.Color(255, 255, 255));
        quickSell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quickSellMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                quickSellMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                quickSellMouseExited(evt);
            }
        });
        quickSell.setLayout(new java.awt.GridLayout());

        quickSellTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        quickSellTxt.setForeground(new java.awt.Color(0, 102, 204));
        quickSellTxt.setText("Quick sell");
        quickSell.add(quickSellTxt);

        manage.setBackground(new java.awt.Color(255, 255, 255));
        manage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageMouseExited(evt);
            }
        });
        manage.setLayout(new java.awt.GridLayout());

        manageTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        manageTxt.setForeground(new java.awt.Color(0, 102, 204));
        manageTxt.setText("Manage");
        manage.add(manageTxt);

        logout.setBackground(new java.awt.Color(255, 255, 255));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        logout.setLayout(new java.awt.GridLayout());

        logoutTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        logoutTxt.setForeground(new java.awt.Color(0, 102, 204));
        logoutTxt.setText("Logout");
        logout.add(logoutTxt);

        javax.swing.GroupLayout buttonsPaneLayout = new javax.swing.GroupLayout(buttonsPane);
        buttonsPane.setLayout(buttonsPaneLayout);
        buttonsPaneLayout.setHorizontalGroup(
            buttonsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 395, Short.MAX_VALUE)
                .addComponent(quickStock, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quickSell, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manage, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );
        buttonsPaneLayout.setVerticalGroup(
            buttonsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPaneLayout.createSequentialGroup()
                .addGroup(buttonsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quickSell, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(quickStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainContent.add(buttonsPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 459, -1, 40));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setToolTipText("");
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("tgretggfdsfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setFocusable(false);
        jTextArea1.setRequestFocusEnabled(false);
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextArea1MouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea1);

        mainContent.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 380, 150));

        root.add(mainContent, java.awt.BorderLayout.CENTER);

        getContentPane().add(root);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBarMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_searchBarMouseEntered

    private void searchBarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBarMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_searchBarMouseExited

    private void searchBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_searchBarMouseClicked

    private void searchButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseEntered
        // TODO add your handling code here:
        buttonHoverBehaviour(searchButton,searchButtonTxt,HOVERCOLOR,WHITE);
    }//GEN-LAST:event_searchButtonMouseEntered

    private void searchButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseExited
        // TODO add your handling code here:
        buttonExitBehaviour(searchButton,searchButtonTxt,WHITE,ORIGINALTEXTCOLOR);
    }//GEN-LAST:event_searchButtonMouseExited

    private void quickStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quickStockMouseEntered
        // TODO add your handling code here:
        buttonHoverBehaviour(quickStock,quickStockTxt,HOVERCOLOR,WHITE);
    }//GEN-LAST:event_quickStockMouseEntered

    private void quickStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quickStockMouseExited
        // TODO add your handling code here:
        buttonExitBehaviour(quickStock,quickStockTxt,WHITE,ORIGINALTEXTCOLOR);
    }//GEN-LAST:event_quickStockMouseExited

    private void quickSellMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quickSellMouseEntered
        // TODO add your handling code here:
         buttonHoverBehaviour(quickSell,quickSellTxt,HOVERCOLOR,WHITE);
    }//GEN-LAST:event_quickSellMouseEntered

    private void quickSellMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quickSellMouseExited
        // TODO add your handling code here:
        buttonExitBehaviour(quickSell,quickSellTxt,WHITE,ORIGINALTEXTCOLOR);
    }//GEN-LAST:event_quickSellMouseExited

    private void manageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageMouseEntered
        // TODO add your handling code here:
        buttonHoverBehaviour(manage,manageTxt,HOVERCOLOR,WHITE);
    }//GEN-LAST:event_manageMouseEntered

    private void manageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageMouseExited
        // TODO add your handling code here:
        buttonExitBehaviour(manage,manageTxt,WHITE,ORIGINALTEXTCOLOR);
    }//GEN-LAST:event_manageMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        buttonHoverBehaviour(logout,logoutTxt,RED,WHITE);
        
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        buttonExitBehaviour(logout,logoutTxt,WHITE,ORIGINALTEXTCOLOR);
        
    }//GEN-LAST:event_logoutMouseExited

    private void productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_productsMouseClicked

    private void quickStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quickStockMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_quickStockMouseClicked

    private void manageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_manageMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutMouseClicked

    private void quickSellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quickSellMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_quickSellMouseClicked

    private void jTextArea1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MouseEntered
        // TODO add your handling code here:
        jTextArea1.setCursor(NORMAL);
    }//GEN-LAST:event_jTextArea1MouseEntered

    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }
    
    public void buttonHoverBehaviour(JPanel button,JLabel text,Color backgroundColor,Color textColor){
        button.setBackground(backgroundColor);
        button.setCursor(HAND);
        text.setForeground(textColor);
        
    
    
    
    
    }
        public void buttonExitBehaviour(JPanel button,JLabel text, Color backgroundColor,Color textColor){
        button.setBackground(backgroundColor);
        text.setForeground(textColor);
        
    
    
    
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPane;
    private javax.swing.JLabel employeeImage;
    private javax.swing.JLabel employeeInfo;
    private javax.swing.JPanel employeePicPane;
    private javax.swing.JPanel imagePane;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel logout;
    private javax.swing.JLabel logoutTxt;
    private javax.swing.JPanel mainContent;
    private javax.swing.JPanel manage;
    private javax.swing.JLabel manageTxt;
    private javax.swing.JLabel productImage;
    private javax.swing.JList<String> products;
    private javax.swing.JPanel quickSell;
    private javax.swing.JLabel quickSellTxt;
    private javax.swing.JPanel quickStock;
    private javax.swing.JLabel quickStockTxt;
    private javax.swing.JPanel root;
    private javax.swing.JTextField searchBar;
    private javax.swing.JPanel searchButton;
    private javax.swing.JLabel searchButtonTxt;
    // End of variables declaration//GEN-END:variables
}
