/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package localinventorymanager.Classes;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.*;
/**
 *
 * @author XD
 */
public class App extends javax.swing.JFrame {
    Color white=new Color(255,255,255);
    Color hoverColor=new Color(99, 190, 255);
    Color originalTextColor=new Color(0,102,204);
    Cursor hand=new Cursor(Cursor.HAND_CURSOR);
    /**
     * Creates new form App
     */
    public App() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        root = new javax.swing.JPanel();
        mainContent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        products = new javax.swing.JList<>();
        imagePane = new javax.swing.JPanel();
        productImage = new javax.swing.JLabel();
        searchBar = new javax.swing.JTextField();
        searchButton = new javax.swing.JPanel();
        searchButtonTxt = new javax.swing.JLabel();
        employeeInfo = new javax.swing.JLabel();
        employeePicPane = new javax.swing.JPanel();
        employeeImage = new javax.swing.JLabel();
        buttonsPane = new javax.swing.JPanel();
        quickStock = new javax.swing.JPanel();
        quickStockTxt = new javax.swing.JLabel();
        quickSell = new javax.swing.JPanel();
        quickSellTxt = new javax.swing.JLabel();
        manage = new javax.swing.JPanel();
        manageTxt = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout());

        root.setBackground(new java.awt.Color(51, 0, 51));
        root.setLayout(new java.awt.BorderLayout());

        mainContent.setBackground(new java.awt.Color(0, 102, 153));
        mainContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        products.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(products);

        mainContent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 124, 498, 209));

        imagePane.setBackground(new java.awt.Color(255, 255, 255));
        imagePane.setLayout(new java.awt.GridLayout());

        productImage.setText("imagen");
        imagePane.add(productImage);

        mainContent.add(imagePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 124, 382, 249));

        searchBar.setText("Search Product");
        searchBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchBarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchBarMouseExited(evt);
            }
        });
        mainContent.add(searchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 351, 353, 20));

        searchButton.setBackground(new java.awt.Color(255, 255, 255));
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchButtonMouseExited(evt);
            }
        });
        searchButton.setLayout(new java.awt.GridLayout());

        searchButtonTxt.setForeground(new java.awt.Color(0, 102, 204));
        searchButtonTxt.setText("Search product");
        searchButton.add(searchButtonTxt);

        mainContent.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 351, 133, 22));

        employeeInfo.setText("Bienvenido usuario");
        mainContent.add(employeeInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 20, -1, -1));

        employeePicPane.setBackground(new java.awt.Color(255, 255, 255));

        employeeImage.setBackground(new java.awt.Color(255, 255, 255));
        employeeImage.setText("Employee pic");

        javax.swing.GroupLayout employeePicPaneLayout = new javax.swing.GroupLayout(employeePicPane);
        employeePicPane.setLayout(employeePicPaneLayout);
        employeePicPaneLayout.setHorizontalGroup(
            employeePicPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePicPaneLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(employeeImage)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        employeePicPaneLayout.setVerticalGroup(
            employeePicPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeePicPaneLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(employeeImage)
                .addGap(39, 39, 39))
        );

        mainContent.add(employeePicPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 6, -1, -1));

        buttonsPane.setBackground(new java.awt.Color(0, 102, 153));
        buttonsPane.setForeground(new java.awt.Color(102, 255, 102));

        quickStock.setBackground(new java.awt.Color(255, 255, 255));
        quickStock.setLayout(new java.awt.GridLayout());

        quickStockTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        quickStockTxt.setForeground(new java.awt.Color(0, 102, 204));
        quickStockTxt.setText("Quick stock");
        quickStock.add(quickStockTxt);

        quickSell.setBackground(new java.awt.Color(255, 255, 255));
        quickSell.setLayout(new java.awt.GridLayout());

        quickSellTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        quickSellTxt.setForeground(new java.awt.Color(0, 102, 204));
        quickSellTxt.setText("Quick sell");
        quickSell.add(quickSellTxt);

        manage.setBackground(new java.awt.Color(255, 255, 255));
        manage.setLayout(new java.awt.GridLayout());

        manageTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        manageTxt.setForeground(new java.awt.Color(0, 102, 204));
        manageTxt.setText("Manage");
        manage.add(manageTxt);

        javax.swing.GroupLayout buttonsPaneLayout = new javax.swing.GroupLayout(buttonsPane);
        buttonsPane.setLayout(buttonsPaneLayout);
        buttonsPaneLayout.setHorizontalGroup(
            buttonsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPaneLayout.createSequentialGroup()
                .addContainerGap(511, Short.MAX_VALUE)
                .addComponent(quickStock, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quickSell, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manage, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );
        buttonsPaneLayout.setVerticalGroup(
            buttonsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsPaneLayout.createSequentialGroup()
                .addGroup(buttonsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(quickSell, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(quickStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainContent.add(buttonsPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 459, -1, 40));

        root.add(mainContent, java.awt.BorderLayout.CENTER);

        getContentPane().add(root);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBarMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_searchBarMouseEntered

    private void searchBarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBarMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_searchBarMouseExited

    private void searchBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_searchBarMouseClicked

    private void searchButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseEntered
        // TODO add your handling code here:
        buttonHoverBehaviour(searchButton,searchButtonTxt,hoverColor,white);
    }//GEN-LAST:event_searchButtonMouseEntered

    private void searchButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseExited
        // TODO add your handling code here:
        buttonExitBehaviour(searchButton,searchButtonTxt,white,originalTextColor);
    }//GEN-LAST:event_searchButtonMouseExited

    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }
    
    public void buttonHoverBehaviour(JPanel button,JLabel text,Color backgroundColor,Color textColor){
        button.setBackground(backgroundColor);
        button.setCursor(hand);
        text.setForeground(textColor);
        
    
    
    
    
    }
        public void buttonExitBehaviour(JPanel button,JLabel text, Color backgroundColor,Color textColor){
        button.setBackground(backgroundColor);
        text.setForeground(textColor);
        
    
    
    
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPane;
    private javax.swing.JLabel employeeImage;
    private javax.swing.JLabel employeeInfo;
    private javax.swing.JPanel employeePicPane;
    private javax.swing.JPanel imagePane;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainContent;
    private javax.swing.JPanel manage;
    private javax.swing.JLabel manageTxt;
    private javax.swing.JLabel productImage;
    private javax.swing.JList<String> products;
    private javax.swing.JPanel quickSell;
    private javax.swing.JLabel quickSellTxt;
    private javax.swing.JPanel quickStock;
    private javax.swing.JLabel quickStockTxt;
    private javax.swing.JPanel root;
    private javax.swing.JTextField searchBar;
    private javax.swing.JPanel searchButton;
    private javax.swing.JLabel searchButtonTxt;
    // End of variables declaration//GEN-END:variables
}
